aydcs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aydcs_app.urls', namespace='home'))
]

aydcs_app/urls.py
from django.urls import path
from . import views

app_name = 'aydcs_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('cours', views.cours, name='cours'),
    path('a_propos', views.a_propos, name='a_propos'),
    path('galerie', views.galerie, name='galerie'),
    path('contact', views.contact, name='contact'),
    path('login', views.login, name='login'),
    path('portail', views.portail, name='portail'),
    path('message/<str:pk>/', views.message, name='message'),
    path('delete/<str:pk>/', views.delete, name='delete'),
    path('delete_essai/<str:pk>/', views.delete_essai, name='delete_essai'),
    path('logout', views.logoutPage, name="logout"),
    
]

aydcs_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class info(models.Model):

    nom = models.CharField(max_length=150)
    email = models.EmailField(max_length=200)
    sujet = models.CharField(max_length=500)
    message = models.TextField(max_length=4500)
    temps = models.CharField(max_length=100)

    def __str__(self):
        return str(self.nom)


class essai(models.Model):

    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    telephone = models.CharField(max_length=50)
    cours = models.CharField(max_length=20)
    timesend = models.CharField(max_length=60)
    def __str__(self):
        return str(self.nom)
    

class coursVa(models.Model):
    coursValid = models.CharField(max_length=40)
    def __str__(self):
        return str(self.coursValid)

aydcs_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import info, essai

class infoRecu(ModelForm):
    class Meta:
        model = info
        fields = '__all__'

class essaiRecu(ModelForm):
    class Meta:
        model = essai
        fields = '__all__'

aydcs_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as dj_login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .decorators import unauthenticated_user
from .models import info, essai, coursVa
from .forms import infoRecu, essaiRecu

# Create your views here.

def home(request):
    coursList = coursVa.objects.all()
    if request.method == 'POST':
        form2 = essaiRecu(request.POST)
        if form2.is_valid():
            form2.save() 
    

    else:
        form2 = essaiRecu()

    return render(request, 'index.html', {'ess': essaiRecu, 'coursList': coursList})

def cours(request):
    coursList = coursVa.objects.all()
    if request.method == 'POST':
        form2 = essaiRecu(request.POST)
        if form2.is_valid():
            form2.save() 
    

    else:
        form2 = essaiRecu()

    return render(request, 'cours.html', {'ess': essaiRecu, 'coursList': coursList})

def a_propos(request):

    return render(request, 'about.html', {})

def galerie(request):

    return render(request, 'galerie.html', {})

def contact(request):
    if request.method == 'POST':
        form = infoRecu(request.POST)
        if form.is_valid():
            form.save() 
    

    else:
        form = infoRecu()

    return render(request, 'contact.html', {'msg': infoRecu})

#admin View

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
                dj_login(request, user)
                return redirect('/portail')
        else:
            return redirect('/login')
    return render(request, 'login/index.html', {})


def logoutPage(request):

    logout(request)
    return redirect('/')


@login_required
def portail(request):
    msg = info.objects.all()
    dmn = essai.objects.all()
    context = {
        'msg': msg,
        'dmn': dmn,
    }

    return render(request, 'portail/received.html', context)

@login_required
def message(request, pk):
    rec = info.objects.get(id=pk)

    return render(request, 'portail/message.html', {'rec': rec})

@login_required
def delete(request, pk):
    rec = get_object_or_404(info, pk=pk)  # Get your current cat

    if request.method == 'POST':         # If method is POST,
        rec.delete()                     # delete the cat.
        return redirect('/portail')             # Finally, redirect to the homepage.

    return render(request, 'portail/received.html', {'rec': rec})

@login_required
def delete_essai(request, pk):
    ess = get_object_or_404(essai, pk=pk)  # Get your current cat

    if request.method == 'POST':         # If method is POST,
        ess.delete()                     # delete the cat.
        return redirect('/portail')             # Finally, redirect to the homepage.

    return render(request, 'portail/received.html', {'ess': ess})

aydcs_app/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AYDCS - Centre De Langues Et Soutien Scolaire</title>
    <link rel="shortcut icon" href="{% static 'images/aydcs.png' %}" type="image/x-icon">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
	  <div class="bg-top navbar-light">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-center align-items-stretch">
    			<div class="col-md-4 d-flex align-items-center py-4">
    				<a class="navbar-brand" href="{% url 'aydcs_app:home' %}"> <img src="{% static 'images/aydcs.png' %}" width="64px" height="64px"> <span>AYDCS CENTER</span></a>
    			</div>
	    		<div class="col-lg-8 d-block">
		    		<div class="row d-flex">
                        <a href="mailto:aydcs01@gmail.com">
					    <div class="col-md d-flex topper align-items-center align-items-stretch py-md-4">
					    	<div class="icon d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
					    	<div class="text">
					    		<span>Email</span>
						    	<span>aydcs01@gmail.com</span>
						    </div>
                        </div>
                    </a>
                    <a href="tel:+212624984773">
					    <div class="col-md d-flex topper align-items-center align-items-stretch py-md-4">
					    	<div class="icon d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <div class="text">
						    	<span>Tel</span>
						    	<span>Numero: +212 624 984 773</span>
						    </div>
                        </div>
                    </a>
					    <div class="col-md topper d-flex align-items-center justify-content-end">
					    	<p class="mb-0">
					    		<a href="{% url 'aydcs_app:cours' %}" class="btn py-2 px-3 btn-primary d-flex align-items-center justify-content-center">
					    			<span>Nous Rejoindre</span>
					    		</a>
					    	</p>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center px-4">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
	        	<li class="nav-item active"><a href="{% url 'aydcs_app:home' %}" class="nav-link pl-0">Acceuil</a></li>
	        	<li class="nav-item"><a href="{% url 'aydcs_app:cours' %}" class="nav-link">Cours</a></li>
	        	<li class="nav-item"><a href="{% url 'aydcs_app:a_propos' %}" class="nav-link">A propos</a></li>
	        	<li class="nav-item"><a href="{% url 'aydcs_app:galerie' %}" class="nav-link">Galerie</a></li>
	          <li class="nav-item"><a href="{% url 'aydcs_app:contact' %}" class="nav-link">Nous Contactez</a></li>
	        </ul>
	      </div>
	    </div>
    </nav>
    

    <!-- END nav -->
    
{% block body %}

{% endblock body %}

		
    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Plus D'info ?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Imm N°470,lotissement riad ismailia 3 éme et 4 éme étage N°6-8 Meknès 50000</span></li>
	                <li><a href="tel:+212624984773"><span class="icon icon-phone"></span><span class="text">+212 624 984 773</span></a></li>
	                <li><a href="mailto:aydcs01@gmail.com"><span class="icon icon-envelope"></span><span class="text">aydcs01@gmail.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">

          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5 ml-md-4">
              <h2 class="ftco-heading-2">Liens</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'aydcs_app:home' %}"><span class="ion-ios-arrow-round-forward mr-2"></span>Acceuil</a></li>
                <li><a href="{% url 'aydcs_app:a_propos' %}"><span class="ion-ios-arrow-round-forward mr-2"></span>A Propos</a></li>
                <li><a href="{% url 'aydcs_app:cours' %}"><span class="ion-ios-arrow-round-forward mr-2"></span>Cours</a></li>
                <li><a href="{% url 'aydcs_app:galerie' %}"><span class="ion-ios-arrow-round-forward mr-2"></span>Galerie</a></li>
                <li><a href="{% url 'aydcs_app:contact' %}"><span class="ion-ios-arrow-round-forward mr-2"></span>Nous Contactez</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">

            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2 mb-0">Connect With Us</h2>
            	<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                
                <li class="ftco-animate"><a href="https://www.facebook.com/Center-AYDCS-1065392960283239"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="https://www.instagram.com/aydcs_c/"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> Tout Droit reservez | Plus D'info Contactez <a href="https://redabenhamid.herokuapp.com" target="_blank" style="color: rgb(191, 59, 218);">Reda Benhamid</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>



  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD20YVoCxUaEOx7SQubDQ4oyR55cpv5b1o&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
    
  </body>
</html>

aydcs_app/templates/portail/mainp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="shortcut icon" href="{% static 'images/aydcs.png' %}" type="image/x-icon">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    AYDCS CENTER
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'portail/assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'portail/assets/demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo"><a href="#" class="simple-text logo-normal"></a><img src="{% static 'images/aydcs.png' %}" style="width: 64px; height: auto;"/>
          AYDCS CENTER
        </a></div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'aydcs_app:portail' %}">
              <i class="material-icons">dashboard</i>
              <p>Acceuil</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'aydcs_app:logout' %}">
              <i class="material-icons">login</i>
              <p>Se Deconnecter</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand"><h2>Message Recu</h2></a>
          </div>
          <div class="collapse navbar-collapse justify-content-end">
            
            </form>
            <ul class="navbar-nav">
              
              
              
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      {% block body %}


      
      {% endblock body %}
      <footer class="footer">
        <div class="container-fluid">
          
          <div class="copyright float-right">
            <script>
              document.write(new Date().getFullYear())
            </script> &copy; Tout Droits Reservez Par | 
            <a href="https://redabenhamid.herokuapp.com" target="_blank">Reda Benhamid</a>
          </div>
        </div>
      </footer>
    </div>
  </div>
  
  <!--   Core JS Files   -->
  <script src="../assets/js/core/jquery.min.js"></script>
  <script src="../assets/js/core/popper.min.js"></script>
  <script src="../assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="../assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="../assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="../assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="../assets/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="../assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="../assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="../assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="../assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="../assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="../assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="../assets/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="../assets/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="../assets/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="../assets/js/plugins/arrive.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="../assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="../assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="../assets/demo/demo.js"></script>
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
</body>

</html>

aydcs_app/templates/portail/received.html
{% extends 'portail/mainp.html' %}

{% block body %}



      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Message Recu</h4>
                  <p class="card-category">Source Des Message Page De Contact</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Date
                        </th>
                        <th>
                          Nom
                        </th>
                        <th>
                          Email
                        </th>
                        <th>
                          Sujet
                        </th>
                        <th>
                          Voir Message
                        </th>
                        <th>
                          Supprimer
                        </th>
                      </thead>
                      <tbody>
                        {% for m in msg %}
                        <tr>
                          <td>
                            {{m.temps}}
                          </td>
                          <td>
                            {{m.nom}}
                          </td>
                          <td>
                            {{m.email}}
                          </td>
                          <td>
                            {{m.sujet}}
                          </td>
                          <td class="text-primary">
                            <a href="{% url 'aydcs_app:message' m.pk %}">
                            <button class="btn btn-primary btn-round">Voir</button>
                          </a>
                          </td>
                          <td class="text-primary">
                            <form action="{% url 'aydcs_app:delete' m.pk %}" method="POST">
                              {% csrf_token %}
                            <button class="btn btn-primary btn-round">Supp</button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Demande Essai</h4>
                  <p class="card-category">Source Des Demande Page De Cours</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Date
                        </th>
                        <th>
                          Nom
                        </th>
                        <th>
                          Prenom
                        </th>
                        <th>
                          Telephone
                        </th>
                        <th>
                          Matiere
                        </th>
                        <th>
                          Supprimer
                        </th>
                      </thead>
                      <tbody>
                        {% for m in dmn %}
                        <tr>
                          <td>
                            {{m.timesend}}
                          </td>
                          <td>
                            {{m.nom}}
                          </td>
                          <td>
                            {{m.prenom}}
                          </td>
                          <td>
                            {{m.telephone}}
                          </td>
                          <td>
                            {{m.cours}}
                          </td>
                          <td class="text-primary">
                            <form action="{% url 'aydcs_app:delete_essai' m.pk %}" method="POST">
                              {% csrf_token %}
                            <button class="btn btn-primary btn-round">Supp</button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      {% endblock body %}